-- AtmoSync: Intermodal Rail Table Structure
-- Backup of ATMOSYNC.RAW.INTERMODAL_RAIL
-- Do not run without checking the target database and schema.

CREATE TABLE IF NOT EXISTS ATMOSYNC.RAW.INTERMODAL_RAIL (
    SHIPMENT_ID VARCHAR(20),
    TRANSPORT_MODE VARCHAR(50),
    RECORDED_DATE DATE,
    RECORDED_TIME TIME(9),
    RECORDED_DATETIME TIMESTAMP_NTZ(9),
    ORIGIN_LOCATION VARCHAR(100),
    DESTINATION_LOCATION VARCHAR(100),
    CARGO_TYPE VARCHAR(50),
    TEMPERATURE_CELSIUS FLOAT,
    HUMIDITY_PERCENTAGE FLOAT,
    VIBRATION_LEVEL FLOAT,
    PRESSURE_KPA FLOAT,
    EXPOSURE_DURATION_HOURS FLOAT,
    DOOR_OPEN_COUNT NUMBER(38,0),
    SALINITY_PPT FLOAT,
    THERMAL_LEAKAGE_SCORE FLOAT,
    SPOILAGE_RISK_PERCENT FLOAT,
    REMAINING_SHELF_LIFE_DAYS FLOAT,
    SPOILAGE_STATUS VARCHAR(20)
);