CREATE DATABASE IF NOT EXISTS ATMOSYNC_DB;

CREATE SCHEMA IF NOT EXISTS ATMOSYNC_DB.RAW;

CREATE SCHEMA IF NOT EXISTS ATMOSYNC_DB.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS ATMOSYNC_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;