SELECT COUNT(*)
FROM ATMOSYNC_DB.RAW.RAW_SHIPMENTS;

SELECT *
FROM ATMOSYNC_DB.RAW.RAW_SHIPMENTS
LIMIT 10;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(spoilage_risk_percent >= 50) AS at_risk_shipments
FROM ATMOSYNC_DB.RAW.RAW_SHIPMENTS;