{{ config(materialized='table') }}

SELECT
    SHIPMENT_ID,
    RECORDED_DATETIME,
    ORIGIN_LOCATION,
    DESTINATION_LOCATION,
    CARGO_TYPE,
    TEMPERATURE_CELSIUS,
    HUMIDITY_PERCENTAGE,
    VIBRATION_LEVEL,
    THERMAL_LEAKAGE_SCORE,
    SPOILAGE_RISK_PERCENT,
    REMAINING_SHELF_LIFE_DAYS,
    SPOILAGE_STATUS,

    CASE
        WHEN SPOILAGE_RISK_PERCENT >= 70 THEN 'High'
        WHEN SPOILAGE_RISK_PERCENT >= 40 THEN 'Medium'
        ELSE 'Low'
    END AS RISK_CATEGORY

FROM {{ ref('stg_intermodal_rail') }}