{{ config(materialized='table') }}

SELECT
    ORIGIN_LOCATION,
    DESTINATION_LOCATION,
    COUNT(*) AS SHIPMENT_COUNT,
    ROUND(AVG(SPOILAGE_RISK_PERCENT), 2) AS AVERAGE_SPOILAGE_RISK,
    ROUND(AVG(REMAINING_SHELF_LIFE_DAYS), 2) AS AVERAGE_SHELF_LIFE

FROM {{ ref('stg_intermodal_rail') }}

GROUP BY
    ORIGIN_LOCATION,
    DESTINATION_LOCATION