{{ config(materialized='table') }}

SELECT
    SHIPMENT_ID,
    TRANSPORT_MODE,
    RECORDED_DATE,
    RECORDED_TIME,
    RECORDED_DATETIME,
    ORIGIN_LOCATION,
    DESTINATION_LOCATION,
    CARGO_TYPE,
    TEMPERATURE_CELSIUS,
    HUMIDITY_PERCENTAGE,
    VIBRATION_LEVEL,
    PRESSURE_KPA,
    EXPOSURE_DURATION_HOURS,
    DOOR_OPEN_COUNT,
    SALINITY_PPT,
    THERMAL_LEAKAGE_SCORE,
    SPOILAGE_RISK_PERCENT,
    REMAINING_SHELF_LIFE_DAYS,
    SPOILAGE_STATUS
FROM {{ ref('stg_intermodal_rail') }}