{{ config(materialized='table') }}

SELECT
    CARGO_TYPE,
    SPOILAGE_STATUS,
    COUNT(*) AS TOTAL_SHIPMENTS,
    ROUND(AVG(SPOILAGE_RISK_PERCENT), 2) AS AVG_SPOILAGE_RISK,
    ROUND(AVG(REMAINING_SHELF_LIFE_DAYS), 2) AS AVG_SHELF_LIFE_DAYS,
    ROUND(AVG(TEMPERATURE_CELSIUS), 2) AS AVG_TEMPERATURE,
    ROUND(AVG(HUMIDITY_PERCENTAGE), 2) AS AVG_HUMIDITY
FROM {{ ref('stg_intermodal_rail') }}
GROUP BY
    CARGO_TYPE,
    SPOILAGE_STATUS